"""v0.0.1

Revision ID: 98f0eff19af6
Revises: 
Create Date: 2025-04-30 11:44:49.397024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f0eff19af6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'error', 'not_logged_in', 'no_connection', 'stopped', name='syncstatus'), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('sync_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('coretools', 'qcodes', 'quantify', 'fileBase', 'labber', name='syncsourcetypes'), nullable=False),
    sa.Column('status', sa.Enum('synchronizing', 'synchronized', 'error', 'paused', name='syncsourcestatus'), nullable=False),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('items_synchronized', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('default_scope', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_source_id', sa.Integer(), nullable=False),
    sa.Column('dataIdentifier', sa.String(), nullable=False),
    sa.Column('scopeIdentifier', sa.String(), nullable=True),
    sa.Column('datasetUUID', sa.Uuid(), nullable=False),
    sa.Column('syncPriority', sa.Float(), nullable=False),
    sa.Column('synchronized', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sync_record', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sync_source_id'], ['sync_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datasetUUID'),
    sa.UniqueConstraint('sync_source_id', 'dataIdentifier', name='sync_source_did_constraint_sync_items')
    )
    op.create_index('failed_upload_index', 'sync_items', ['sync_source_id', 'attempts'], unique=False)
    op.create_index(op.f('ix_sync_items_dataIdentifier'), 'sync_items', ['dataIdentifier'], unique=False)
    op.create_index(op.f('ix_sync_items_syncPriority'), 'sync_items', ['syncPriority'], unique=False)
    op.create_index('read_item_index', 'sync_items', ['sync_source_id', 'scopeIdentifier', 'synchronized', 'dataIdentifier'], unique=False)
    op.create_index('sync_upload_index', 'sync_items', ['sync_source_id', 'attempts', 'synchronized'], unique=False)
    op.create_table('sync_scope_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_source_id', sa.Integer(), nullable=False),
    sa.Column('scope_identifier', sa.String(), nullable=False),
    sa.Column('scope_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sync_source_id'], ['sync_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_source_id', 'scope_identifier', name='sync_source_did_constraint_scope_mapping')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_scope_mappings')
    op.drop_index('sync_upload_index', table_name='sync_items')
    op.drop_index('read_item_index', table_name='sync_items')
    op.drop_index(op.f('ix_sync_items_syncPriority'), table_name='sync_items')
    op.drop_index(op.f('ix_sync_items_dataIdentifier'), table_name='sync_items')
    op.drop_index('failed_upload_index', table_name='sync_items')
    op.drop_table('sync_items')
    op.drop_table('sync_sources')
    op.drop_table('sync_status')
    # ### end Alembic commands ###
